Vagrant.configure(2) do |config|

# konfigurasi box untuk sistem operasi ubuntu trusty 64 bit
	config.vm.box = "ubuntu/xenial64"
	
	config.vm.provider "virtualbox" do |vb|
	
# konfigurasi virtual box dengan ram 1 GB
	vb.memory = "1024"

# konfigurasi otomatimasi
	config.vm.provision "shell", path: "otomasi-landing-page.sh"

# konfigurasi networking	
	config.vm.network "private_network", ip: "192.168.1.236"

   end
end
